// lib/distribute.js
// Sends the generated report to all stakeholders via email
// Uses Resend.com — free tier covers 3,000 emails/month

const RESEND_API_KEY   = process.env.RESEND_API_KEY;
const FROM_EMAIL       = process.env.FROM_EMAIL;
const REPORT_RECIPIENTS = process.env.REPORT_RECIPIENTS;

async function distributeReport(weekLabel, reportMarkdown) {
  if (!RESEND_API_KEY || !REPORT_RECIPIENTS) {
    console.log('Email not configured — skipping distribution');
    return { skipped: true };
  }

  const recipients = REPORT_RECIPIENTS.split(',').map(e => e.trim());

  // Convert basic markdown to readable HTML email
  const htmlBody = reportMarkdown
    .replace(/^# (.+)$/gm,   '<h1 style="font-family:Georgia,serif;font-size:1.6em;margin:24px 0 8px">$1</h1>')
    .replace(/^## (.+)$/gm,  '<h2 style="font-family:Georgia,serif;font-size:1.1em;text-transform:uppercase;letter-spacing:2px;color:#888;margin:24px 0 8px">$1</h2>')
    .replace(/^### (.+)$/gm, '<h3 style="font-size:.95em;font-weight:700;margin:16px 0 4px">$1</h3>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\n\n/g, '<br><br>');

  const emailHtml = `
    <div style="max-width:680px;margin:0 auto;font-family:Georgia,serif;color:#1a1a1a;padding:40px 32px">
      <div style="border-bottom:2px solid #1a1a1a;padding-bottom:12px;margin-bottom:32px">
        <div style="font-family:sans-serif;font-size:.65em;letter-spacing:3px;text-transform:uppercase;color:#c9a84c;margin-bottom:4px">Field Intelligence OS</div>
        <div style="font-size:1.2em;font-weight:700">Kanazi Rural Connectivity — ${weekLabel}</div>
      </div>
      ${htmlBody}
      <div style="border-top:1px solid #e0e0e0;margin-top:40px;padding-top:16px;font-family:sans-serif;font-size:.7em;color:#aaa;letter-spacing:1px">
        Generated by Field Intelligence OS · Loop Institute · Kigali
      </div>
    </div>
  `;

  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${RESEND_API_KEY}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      from: FROM_EMAIL,
      to:   recipients,
      subject: `Kanazi Field Report — ${weekLabel}`,
      html: emailHtml
    })
  });

  if (!res.ok) {
    const err = await res.json();
    console.error('Email send failed:', err);
    return { error: err.message };
  }

  return { sent: true, recipients };
}

module.exports = { distributeReport };