// lib/distribute.js — fixed markdown rendering + asterisk bug

const RESEND_API_KEY    = process.env.RESEND_API_KEY;
const FROM_EMAIL        = process.env.FROM_EMAIL;
const REPORT_RECIPIENTS = process.env.REPORT_RECIPIENTS;

function mdToEmailHtml(md) {
  return md
    .replace(/^# (.+)$/gm,   '<h1 style="font-family:Georgia,serif;font-size:1.4em;border-bottom:2px solid #1a1a1a;padding-bottom:10px;margin:24px 0 16px">$1</h1>')
    .replace(/^## (.+)$/gm,  '<h2 style="font-family:sans-serif;font-size:.7em;letter-spacing:2px;text-transform:uppercase;color:#888;border-top:1px solid #eee;padding-top:18px;margin:22px 0 10px">$1</h2>')
    .replace(/^### (.+)$/gm, '<h3 style="font-size:.95em;font-weight:700;margin:14px 0 4px">$1</h3>')
    .replace(/^\* (.+)$/gm,  '<li style="margin-bottom:4px;line-height:1.6">$1</li>')
    .replace(/^- (.+)$/gm,   '<li style="margin-bottom:4px;line-height:1.6">$1</li>')
    .replace(/(<li.+<\/li>\n?)+/g, m => `<ul style="padding-left:20px;margin:8px 0">${m}</ul>`)
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\n\n/g, '</p><p style="margin-bottom:10px;line-height:1.7">');
}

async function distributeReport(weekLabel, reportMarkdown) {
  if (!RESEND_API_KEY || !REPORT_RECIPIENTS) {
    console.log('Email not configured — skipping');
    return { skipped: true };
  }

  const recipients = REPORT_RECIPIENTS.split(',').map(e => e.trim());
  const bodyHtml   = mdToEmailHtml(reportMarkdown);

  const emailHtml = `
  <div style="max-width:680px;margin:0 auto;font-family:Georgia,serif;color:#1a1a1a;padding:40px 32px">
    <div style="border-bottom:2px solid #1a1a1a;padding-bottom:12px;margin-bottom:28px">
      <div style="font-family:sans-serif;font-size:.6em;letter-spacing:3px;text-transform:uppercase;color:#c9a84c;margin-bottom:4px">Field Intelligence OS</div>
      <div style="font-family:sans-serif;font-size:1em;font-weight:700">Kanazi Rural Connectivity — ${weekLabel}</div>
    </div>
    <p style="margin-bottom:10px;line-height:1.7">${bodyHtml}</p>
    <div style="border-top:1px solid #eee;margin-top:36px;padding-top:14px;font-family:sans-serif;font-size:.6em;letter-spacing:2px;text-transform:uppercase;color:#bbb;text-align:center">
      Generated by Field Intelligence OS · Loop Institute · Kigali
    </div>
  </div>`;

  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${RESEND_API_KEY}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      from:    FROM_EMAIL,
      to:      recipients,
      subject: `Kanazi Field Report — ${weekLabel}`,
      html:    emailHtml
    })
  });

  if (!res.ok) {
    const err = await res.json();
    console.error('Email failed:', err);
    return { error: err.message };
  }
  return { sent: true, recipients };
}

module.exports = { distributeReport };